name: Auto Commit Daily Everyday

on:
  schedule:
    - cron: "*/3 * * * *" # every 3 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create and commit file
        run: |
          export TZ=Asia/Ho_Chi_Minh

          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          FILE_NAME="files/$TIMESTAMP.txt"
          mkdir -p files
          echo "Time commit (UTC+7): $TIMESTAMP" > "$FILE_NAME"

          git config --global user.name "Bot Commit - Le Tien Dat"
          git config --global user.email "attn110601@gmail.com"

          echo "ğŸ“Œ Git status BEFORE commit:"
          git status

          git add "$FILE_NAME"
          git commit -m "Auto commit at $TIMESTAMP" || echo "Nothing to commit"

          echo "ğŸ” Pulling latest from origin/main"
          git pull origin main --rebase || echo "âš ï¸ Pull failed"

          echo "ğŸ“¤ Pushing to GitHub..."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "âš ï¸ Push failed"

          echo "âœ… Commit at $TIMESTAMP (UTC+7)"
